import { Permission } from './permission.enum';
import { Role } from './role.enum';

export const RolePermissions: Record<Role, Permission[]> = {
  [Role.Owner]: [
    Permission.QueueManage,
    Permission.QueueInputVitals,
    Permission.PatientManage,
    Permission.ConsultationStart,
    Permission.OrderFinalize,
    Permission.BillingHandle,
    Permission.McGenerate,
    Permission.McTemplateCustomize,
    Permission.ConsultationTemplateCustomize,
    Permission.PrescriptionTemplateCustomize,
    Permission.SettingsView,
    Permission.StaffManage,
    Permission.GlobalSettingsAccess,
    Permission.ReportsView,
    Permission.ReportIncome,
    Permission.ReportPatientDemographics,
    Permission.ReportNewVsReturning,
    Permission.ReportServicesUsage,
    Permission.ReportDoctorActivity,
    Permission.ReportStaffActivity,
    Permission.ReportQueueActivity,
    Permission.ReportDailySummary,
    Permission.ReportActivityLogs,
    Permission.ReportPaymentBreakdown,
    Permission.ActivityLogsView,
    Permission.SubscriptionManage,
    Permission.BranchSupportAccess,
  ],
  [Role.Admin]: [
    Permission.QueueManage,
    Permission.QueueInputVitals,
    Permission.PatientManage,
    Permission.ConsultationStart,
    Permission.OrderFinalize,
    Permission.BillingHandle,
    Permission.McGenerate,
    Permission.McTemplateCustomize,
    Permission.ConsultationTemplateCustomize,
    Permission.PrescriptionTemplateCustomize,
    Permission.SettingsView,
    Permission.StaffManage,
    Permission.ReportsView,
    Permission.ReportIncome,
    Permission.ReportPatientDemographics,
    Permission.ReportNewVsReturning,
    Permission.ReportServicesUsage,
    Permission.ReportDoctorActivity,
    Permission.ReportStaffActivity,
    Permission.ReportQueueActivity,
    Permission.ReportDailySummary,
    Permission.ReportActivityLogs,
    Permission.ReportPaymentBreakdown,
    Permission.ActivityLogsView,
    Permission.SubscriptionManage,
  ],
  [Role.Staff]: [
    Permission.QueueManage,
    Permission.QueueInputVitals,
    Permission.PatientManage,
    Permission.OrderFinalize,
    Permission.BillingHandle,
    Permission.McGenerate,
    Permission.ReportsView,
    Permission.ReportDailySummary,
  ],
  [Role.Doctor]: [
    Permission.QueueManage,
    Permission.QueueInputVitals,
    Permission.PatientManage,
    Permission.ConsultationStart,
    Permission.McGenerate,
    Permission.ReportsView,
    Permission.ReportDoctorActivity,
  ],
};
